In [1]:
#Importing Libraries

import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [2]:
warnings.filterwarnings('ignore')

In [3]:
#Loading the Dataset
dataset = pd.read_csv("Prep.csv")

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
#Converting Categorical data to Numerical Data
dataset = pd.get_dummies(dataset,dtype = int,drop_first = True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
#Splitting Dependent and Independent Variables
independent = dataset.drop("classification_yes",axis = 1)
dependent = dataset["classification_yes"]

In [8]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [9]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [116]:
#Feature Selection Using Select K Best Algorithm
kBest = SelectKBest(score_func=chi2, k=9)
kBestAlgo = kBest.fit(independent,dependent)
features = kBest.transform(independent)
features

array([[2.00000000e+00, 3.00000000e+00, 0.00000000e+00, ...,
        1.25181556e+01, 3.88689024e+01, 8.40819113e+03],
       [3.00000000e+00, 2.00000000e+00, 0.00000000e+00, ...,
        1.07000000e+01, 3.40000000e+01, 1.23000000e+04],
       [4.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.20000000e+01, 3.40000000e+01, 8.40819113e+03],
       ...,
       [5.14923077e+01, 3.00000000e+00, 0.00000000e+00, ...,
        9.10000000e+00, 2.60000000e+01, 9.20000000e+03],
       [5.14923077e+01, 0.00000000e+00, 0.00000000e+00, ...,
        8.50000000e+00, 3.88689024e+01, 8.40819113e+03],
       [5.14923077e+01, 0.00000000e+00, 0.00000000e+00, ...,
        1.63000000e+01, 5.30000000e+01, 8.50000000e+03]])

In [117]:
kBest

SelectKBest(k=9, score_func=<function chi2 at 0x000001D213487380>)

In [118]:
kBest.get_support()

array([ True, False,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [119]:
#Splitting Training and Testing Dataset
x_train, x_test, y_train, y_test = train_test_split(features,dependent,test_size = 0.20,random_state = 0)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [120]:
log=[]
svml=[]
svmnl=[]
knn=[]
nav=[]
des=[]
rf=[]

In [121]:
#Logistic Regression
lg_regression = LogisticRegression(random_state = 0)
lg_regression.fit(x_train,y_train)
y_pred = lg_regression.predict(x_test)
lg_cm = confusion_matrix(y_test, y_pred)
lg_accuracy = accuracy_score(y_test, y_pred )
lg_classification = classification_report(y_test, y_pred)

log.append(lg_accuracy)

In [122]:
#SVM Linear
svm_regression = SVC(kernel = 'linear', random_state = 0)
svm_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
svm_cm = confusion_matrix(y_test, y_pred)
svm_accuracy = accuracy_score(y_test, y_pred )
svm_classification = classification_report(y_test, y_pred)

svml.append(lg_accuracy)

In [123]:
#SVM RBF
svmnl_regression = SVC(kernel = 'rbf', random_state = 0)
svmnl_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
svmnl_cm = confusion_matrix(y_test, y_pred)
svmnl_accuracy = accuracy_score(y_test, y_pred )
svmnl_classification = classification_report(y_test, y_pred)

svmnl.append(lg_accuracy)

In [124]:
#KNN
knn_regression =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
knn_cm = confusion_matrix(y_test, y_pred)
knn_accuracy = accuracy_score(y_test, y_pred )
knn_classification = classification_report(y_test, y_pred)

knn.append(lg_accuracy)

In [125]:
#Decision Tree
des_regression =  DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
des_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
des_cm = confusion_matrix(y_test, y_pred)
des_accuracy = accuracy_score(y_test, y_pred )
des_classification = classification_report(y_test, y_pred)

des.append(lg_accuracy)

In [126]:
#Naive Baye's
nav_regression = GaussianNB()
nav_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
nav_cm = confusion_matrix(y_test, y_pred)
nav_accuracy = accuracy_score(y_test, y_pred )
nav_classification = classification_report(y_test, y_pred)

nav.append(lg_accuracy)

In [127]:
#Random Forest
rf_regression = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf_regression.fit(x_train,y_train)
y_pred = svm_regression.predict(x_test)
rf_cm = confusion_matrix(y_test, y_pred)
rf_accuracy = accuracy_score(y_test, y_pred )
rf_classification = classification_report(y_test, y_pred)

rf.append(lg_accuracy)

In [128]:
result=dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
for number,index in enumerate(dataframe.index):      
    dataframe['Logistic'][index]=log[number]       
    dataframe['SVMl'][index]=svml[number]
    print(svmnl)
    print(number)
    dataframe['SVMnl'][index]=svmnl[number]
    dataframe['KNN'][index]=knn[number]
    dataframe['Navie'][index]=nav[number]
    dataframe['Decision'][index]=des[number]
    dataframe['Random'][index]=rf[number]

[0.975]
0

In [70]:
# K = 5
dataframe

          Logistic    SVMl   SVMnl     KNN   Navie Decision  Random
ChiSquare   0.9375  0.9375  0.9375  0.9375  0.9375   0.9375  0.9375

In [71]:
independent.columns[kBest.get_support()]

Index(['bgr', 'bu', 'sc', 'pcv', 'wc'], dtype='object')

In [86]:
# K = 6
dataframe

          Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.95  0.95  0.95  0.95  0.95     0.95   0.95

In [87]:
independent.columns[kBest.get_support()]

Index(['al', 'bgr', 'bu', 'sc', 'pcv', 'wc'], dtype='object')

In [101]:
# K = 7
dataframe

          Logistic   SVMl  SVMnl    KNN  Navie Decision Random
ChiSquare    0.975  0.975  0.975  0.975  0.975    0.975  0.975

In [115]:
# K = 8
dataframe

          Logistic   SVMl  SVMnl    KNN  Navie Decision Random
ChiSquare    0.975  0.975  0.975  0.975  0.975    0.975  0.975

In [129]:
# K = 9
dataframe

          Logistic   SVMl  SVMnl    KNN  Navie Decision Random
ChiSquare    0.975  0.975  0.975  0.975  0.975    0.975  0.975